### ISSUE TITLE
Make setting.Provider take a variadic parameters.

### ISSUE THREAD

**Issue by alistairjudson** [intelligentpos/setting#2]
- setting.Provider should take a variadic slice of keys, and return a `map[string]Setting` rather than a single setting. [more info here](https://gobyexample.com/variadic-functions)

- if a setting cannot be found then a nil map should be returned, and error stating which setting cannot be found.
- `setting.CachedProvider`, `setting.AggregateProvider`, and `setting.Filler` will have to be refactored to take this change into account.

- The fallback behaviour of `setting.AggregateProvider` should not change.

- The lifetime of `setting.ExpirableSetting` should still be respected on `setting.CachedProvider`

- Make sure all tests still pass and do not reduce coverage.

**Comment by bborisovs** [comment]
got `setting.Provider` and `setting.Filler` refactored; that includes 100% coverage; 
The plan for today is do as much as I can from the rest; tomorrow's plan is to go over `setting.AggregateProvider` and get some help from @Connor-McGuinness
