### ISSUE TITLE
Refactor setting to provide better errors.

### ISSUE THREAD

**Issue by alistairjudson** [intelligentpos/setting#52]
Currently setting provides two concrete error types. 
`setting.SimpleProviderError` and `setting.FatalProviderError` it's not great, see [here](https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully). 

We're switching on the error type which is smelly, which points to a deficiency, we should probably add a method to `ProviderError` so it becomes something like.
```go
 type ProviderError interface{
	error
	MissingKeys() []string
	FatalError() error
}
```
This way we only have to ask our error if it's fatal or not, by checking if the error is nil or not.

It may be worth at the same time creating a type of map[string]Setting as the return type, so we have the possibility of adding methods to it at some point.
e.g. 
```go
type Settings map[string]Setting
```

This is part of a bit of a refactoring project for 2.0

**Comment by GitCodeOli** [comment]
Read through the blog post - makes sense, will have a crack at this in the morning
